### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [amitjosh/AmitexploringPolka#1]
Hi amitjosh,

Thanks for participating in the challenge. I can't retrieve the needed addresses to verify your submission from the checkContract. Could you please share the checkContract that you used?

Regards
Alberto

**Comment by amitjosh** [comment]
Hi @albertov19 sure. Please find checkContract I used below. 

Regards,
Amit
--------------------------------
pragma solidity ^0.6.0;

import 'https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v3.1.0/contracts/token/ERC20/ERC20.sol';

// This ERC-20 contract mints the specified amount of tokens to the contract creator.
 contract checkContract {
 // address public address1;
 // address public address2;
 // address public addresstoken;
 
 constructor (address address1, address address2, address addresstoken) public {
 address1 = 0x6Be02d1d3665660d22FF9624b7BE0551ee1Ac91b;
 address2 =  0xF778a89195C1167F7a2B807502Bf42a5C5472377;
 addresstoken = 0x5c4242beB94dE30b922f57241f1D02f36e906915;
    }
  }

**Comment by albertov19** [comment]
Hey Amit,

So the check contract is not correct and that is the issue. You are not defining the address1, address2 and addresstoken variables (by the way please use addressToken so that our automatic script runs fine). In solidity you can actually declare a variable with the lines you have just under checkContract{

```
address: variable type
public: visibility
address1: variable name
```
When you make a variable public it means that anyone with the contracts address can check that variable. And when you define a variable you can also set the value:

```
uint public number = 2;
```
I'm creating a unsigned integer (positive number only with no decimals), I made it public so anyone can access it, and I've assigned the value to be 2. This is what you have to do for this part of the excercise.

Regards
Alberto

**Comment by amitjosh** [comment]
Hey @albertov19 ,

Thanks for the explanation. I have updated the checkContract. New Address: 0x50275d3F95E0F2FCb2cAb2Ec7A231aE188d7319d    as per deployment on remix (I have updated it in my submission as well.

Regards,
Amit
===========================================
pragma solidity ^0.6.0;

import 'https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v3.1.0/contracts/token/ERC20/ERC20.sol';

// This ERC-20 contract mints the specified amount of tokens to the contract creator.
 contract checkContract {
    
 address public address1 = 0x6Be02d1d3665660d22FF9624b7BE0551ee1Ac91b;
 address public address2 = 0xF778a89195C1167F7a2B807502Bf42a5C5472377;
 address public addresstoken = 0x5c4242beB94dE30b922f57241f1D02f36e906915;
 
 
 //address1 public address = 0x6Be02d1d3665660d22FF9624b7BE0551ee1Ac91b;
 //address2 public address =  0xF778a89195C1167F7a2B807502Bf42a5C5472377;
 //addresstoken public address = 0x5c4242beB94dE30b922f57241f1D02f36e906915;
   
  }

**Comment by albertov19** [comment]
Hey @amitjosh 

I can't retrieve the address still. Please contact me through discord and I'll help you with your issue @albertov19 .

Regards
Alberto

**Comment by amitjosh** [comment]
sure. I will

**Comment by amitjosh** [comment]
Hi @albertov19 thanks for your support.
Please find the updated checkContract address: 0x39099D08008406fd052871051758D19A5F668656

Thanks
