### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Deploy On Moonbase Alpha Using Truffle

### ISSUE THREAD

**Issue by albertov19** [amitjosh/AmitexploringPolka#2]
Hi amitjosh,

Thanks for your submission also in our Truffle challenge. There is an issue with both of your contracts that you submitted. I'm not sure if you are deploying the contracts on a local node or you are indeed deploying them on Moonbase Alpha. Feel free to reach out in our TestNet channel: https://discord.gg/3ySJemG - from there we'll help you out.

Regards
Alberto

**Comment by amitjosh** [comment]
Hi @albertov19  Have successfully executed the contracts on moonbeam alpha now. 
0xE448f9BC0912C1a9212EA1B18868c6689409774c, 0x4E8d00Ef43a546b2A1eE9790E99342221162bB5A

Please check and let me know.

Thanks,
Amit
